name: App Quality Checks

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths:
      - "app/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: app

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x        

    - name: Installation of Dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm ci --ignore-scripts
      env:
        CI: true

    - name: Unit tests
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm run test
      env:
        CI: true
    
    - name: Vulnerabilities check
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm audit --audit-level=high --production
      env:
        CI: true

    - name: Build test
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm run build
      env:
        CI: true